lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: 'id' # Any of the properties/getters in the user object
    user_id_claim: 'id' # The fieldname used in the JWT payload for the user identity
